services:
  order-service:
    container_name: order_api
    image: rafaelbarros/order-api:1.0
    ports:
      - '${APP_PORT}:8080'
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge