services:
  order-api-prod:
    container_name: order_api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV_FILE: ${ENV_FILE}
    env_file:
      - ${ENV_FILE}
    ports:
      - '${APP_PORT}:8080'
    networks:
      - app_network
    restart: always
    entrypoint: ["/usr/bin/java", "-jar", "/app/app.jar"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${APP_HOST}:${APP_PORT}/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  app_network:
    driver: bridge