spring:
  application:
    name: order-service
  profiles:
    default: local


server:
  port: 8080
  servlet:
    context-path: /order-service

# banner
application:
  title: ${spring.application.name}
  version: @project.version@
  profile: ${spring.application.profiles.default}

  output:
    ansi:
      enabled: ALWAYS



