services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    user: root
    privileged: true
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./casc.yaml:/var/jenkins_home/casc_configs/jenkins.yaml
      - ./create_pipeline.groovy:/var/jenkins_home/init.groovy.d/create_pipeline.groovy
      - ./add_git_credentials.groovy:/var/jenkins_home/init.groovy.d/add_git_credentials.groovy   
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/jenkins.yaml
      - JENKINS_ADMIN_USER=${JENKINS_ADMIN_USER}
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD}
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/login"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s
    entrypoint: >
      sh -c "chown jenkins:docker /var/run/docker.sock || true &&
             exec /usr/bin/tini -- /usr/local/bin/jenkins.sh"

volumes:
  jenkins_home:

networks:
  app_network:
    driver: bridge
